# Generated by Django 6.0.1 on 2026-05-17 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('years', models.JSONField(default=list)),
                ('streams', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_term', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_sections',
                'ordering': ['name'],
            },
        ),
    ]
