# Generated by Django 6.0.1 on 2026-05-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0002_schoolsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Africa/Kigali', max_length=50)),
                ('school_name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'school_setting',
            },
        ),
    ]
