# Generated by Django 6.0.7 on 2026-07-16 01:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text='Sort order within the day')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'timetable_periods',
                'ordering': ['order'],
            },
        ),
    ]
