# Generated by Django 6.0.7 on 2026-07-19 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0006_dutypost_dutyassignment'),
        ('results', '0006_subject_timetable_weight'),
        ('teacher', '0008_subjectteacherassignment_periods_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningSitting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('supper', 'Supper')], default='lunch', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(help_text='Seats available in this sitting')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dining_sittings',
                'ordering': ['meal', 'order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DiningAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_assignments', to='teacher.class')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_assignments', to='results.academicterm')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dos.diningsitting')),
            ],
            options={
                'db_table': 'dining_assignments',
                'ordering': ['sitting__meal', 'sitting__order'],
                'unique_together': {('sitting', 'term', 'class_obj')},
            },
        ),
    ]
