# Generated by Django 6.0.7 on 2026-08-14 17:29

import apps.dos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0007_diningsitting_diningassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='terms',
            field=models.JSONField(blank=True, default=apps.dos.models.default_terms),
        ),
    ]
