# Generated by Django 6.0.7 on 2026-08-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0008_configurable_school_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
    ]
