# Generated by Django 6.0.7 on 2026-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0009_school_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school-logos/'),
        ),
    ]
