# Generated by Django 6.0.8 on 2026-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0011_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
