# Generated by Django 6.0.8 on 2026-10-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0012_school_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='hold_enrolment_until_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
