# Generated by Django 6.0.8 on 2026-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0013_schoolsetting_hold_enrolment_until_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='auto_fee_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='fee_reminder_every_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='fee_reminder_min_percent',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='fee_reminders_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
