# Generated by Django 6.0.1 on 2026-03-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_pending_email'),
        ('teacher', '0002_reminder_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text='Class to assign the student to upon registration (students only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='teacher.class'),
        ),
    ]
