# Generated by Django 6.0.1 on 2026-06-24 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matron', '0001_initial'),
        ('student', '0003_quiz_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_type', models.CharField(choices=[('weekday', 'Monday – Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('order', models.PositiveSmallIntegerField()),
                ('time', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('is_break', models.BooleanField(default=False)),
                ('break_text', models.CharField(blank=True, max_length=200)),
                ('cell_class', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'matron_boarding_schedule_slots',
                'ordering': ['day_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BoardingScheduleChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('applied', 'Applied')], default='new', max_length=10)),
                ('change_date', models.DateField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_schedule_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matron_boarding_schedule_changes',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_type', models.CharField(choices=[('sickbay_admission', 'Sick Bay Admission'), ('routine_checkup', 'Routine Check-up'), ('medication', 'Medication Dispensed'), ('follow_up', 'Follow-up Visit'), ('injury', 'Injury'), ('discharge', 'Discharge')], max_length=20)),
                ('condition_tag', models.CharField(choices=[('illness', 'Illness'), ('injury', 'Injury'), ('checkup', 'Check-up'), ('followup', 'Follow-up')], max_length=10)),
                ('status', models.CharField(choices=[('in_sick_bay', 'In Sick Bay'), ('observation', 'Observation'), ('cleared', 'Cleared')], default='in_sick_bay', max_length=15)),
                ('visit_datetime', models.DateTimeField()),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('complaint', models.CharField(max_length=255)),
                ('action_taken', models.TextField(blank=True)),
                ('admitted', models.BooleanField(default=False)),
                ('bed_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('notify_parent', models.CharField(choices=[('none', 'No'), ('sms', 'Yes — SMS'), ('call', 'Yes — Call Parent'), ('both', 'Yes — Both')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records_logged', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='student.student')),
            ],
            options={
                'db_table': 'matron_health_records',
                'ordering': ['-visit_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ParentCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_contact', models.CharField(max_length=150)),
                ('comm_type', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS / WhatsApp'), ('email', 'Email'), ('visit', 'In-Person Visit'), ('letter', 'Letter')], max_length=10)),
                ('contacted_at', models.DateTimeField()),
                ('subject', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('completed', 'Completed — parent informed'), ('no_answer', 'No Answer — will retry'), ('message_left', 'Message Left'), ('awaiting_reply', 'Awaiting Parent Reply'), ('sms_sent', 'SMS Sent'), ('email_sent', 'Email Sent')], max_length=20)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('important', 'Important'), ('urgent', 'Urgent')], default='routine', max_length=10)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comms_logged', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications', to='student.student')),
            ],
            options={
                'db_table': 'matron_parent_communications',
                'ordering': ['-contacted_at'],
            },
        ),
    ]
