# Generated by Django 6.0.6 on 2026-07-10 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matron', '0004_medicationschedule_medicationlog'),
        ('student', '0003_quiz_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['status'], name='matron_heal_status_961dec_idx'),
        ),
    ]
