# Generated by Django 6.0.7 on 2026-08-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matron', '0005_healthrecord_matron_heal_status_961dec_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingscheduleslot',
            name='day_type',
            field=models.CharField(choices=[('weekday', 'Monday - Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='notify_parent',
            field=models.CharField(choices=[('none', 'No'), ('sms', 'Yes (SMS)'), ('call', 'Yes (Call Parent)'), ('both', 'Yes (Both)')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentcommunication',
            name='outcome',
            field=models.CharField(choices=[('completed', 'Completed (parent informed)'), ('no_answer', 'No Answer (will retry)'), ('message_left', 'Message Left'), ('awaiting_reply', 'Awaiting Parent Reply'), ('sms_sent', 'SMS Sent'), ('email_sent', 'Email Sent')], max_length=20),
        ),
    ]
