# Generated by Django 6.0.1 on 2026-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_fee_alter_activityenrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
    ]
