# Generated by Django 6.0.8 on 2026-10-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dietary_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
