# Generated by Django 6.0.8 on 2026-10-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('exam', 'Exam Scheduled'), ('attendance', 'Attendance Alert'), ('results', 'Results Ready'), ('timetable', 'Timetable Conflict'), ('staff', 'Staff Status'), ('announcement', 'Announcement'), ('message', 'New Message')], max_length=20),
        ),
    ]
