# Generated by Django 6.0.1 on 2026-02-24 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('positive', 'Positive Report'), ('warning', 'Warning'), ('incident', 'Incident'), ('achievement', 'Achievement')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical')], max_length=20, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('action_taken', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('parents_notified', models.BooleanField(default=False)),
                ('parent_notification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to='students.student')),
                ('witnesses', models.ManyToManyField(blank=True, related_name='witnessed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'behavior_reports',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'date'], name='behavior_re_student_3ff39d_idx'), models.Index(fields=['report_type'], name='behavior_re_report__bb4381_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConductGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Satisfactory'), ('D', 'D - Needs Improvement'), ('F', 'F - Unsatisfactory')], max_length=1)),
                ('positive_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('incident_count', models.IntegerField(default=0)),
                ('achievement_count', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_grades', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.academicterm')),
            ],
            options={
                'db_table': 'conduct_grades',
                'ordering': ['-term__year', '-term__term'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
