# Generated by Django 6.0.1 on 2026-02-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behavior', '0001_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductgrade',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.academicterm'),
        ),
        migrations.AddIndex(
            model_name='behaviorreport',
            index=models.Index(fields=['student', 'date'], name='behavior_re_student_3ff39d_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorreport',
            index=models.Index(fields=['report_type'], name='behavior_re_report__bb4381_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conductgrade',
            unique_together={('student', 'term')},
        ),
    ]
