# Generated by Django 6.0.1 on 2026-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_fee_alter_activityenrollment_student_and_more'),
        ('teacher', '0002_reminder_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='student.student'),
        ),
    ]
