# Generated by Django 6.0.1 on 2026-06-04 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0004_subject_category'),
        ('teacher', '0004_teacherclasslist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('paper', 'Paper'), ('online', 'Online')], default='paper', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('due_date', models.DateField()),
                ('max_score', models.IntegerField()),
                ('questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='teacher.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='results.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
