# Generated by Django 6.0.1 on 2026-06-05 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0004_subject_category'),
        ('student', '0003_quiz_features'),
        ('teacher', '0005_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank')], default='mcq', max_length=20)),
                ('text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('points', models.IntegerField(default=1)),
                ('image', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('student_code', models.CharField(blank=True, max_length=50)),
                ('answers', models.JSONField(default=list)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_score', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_graded', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher.assignment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_submissions', to='student.student')),
            ],
            options={
                'db_table': 'quiz_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
