# Generated by Django 6.0.1 on 2026-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_quiz_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
