# Generated by Django 6.0.7 on 2026-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_questionbank_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectteacherassignment',
            name='periods_per_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
