# Generated by Django 6.0.7 on 2026-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_subjectteacherassignment_periods_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=10),
        ),
    ]
