# Generated by Django 6.0.7 on 2026-08-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_configurable_school_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
