# Generated by Django 6.0.7 on 2026-08-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_assignmentsubmission_file_assignmentsubmission_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
