# Generated by Django 6.0.7 on 2026-08-23 01:14

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def _release_existing_marks(apps, schema_editor):
    """
    Every mark already entered is already visible to its student - it was
    visible the instant it was saved, because nothing gated it. Introducing
    released_at without backfilling would retroactively hide all of them.
    """
    Submission = apps.get_model('teacher', 'AssignmentSubmission')
    Submission.objects.filter(is_graded=True, released_at__isnull=True).update(
        released_at=timezone.now(),
    )


def _unrelease(apps, schema_editor):
    """Reverse: released_at is dropped with the column, so nothing to undo."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_extend_target_grade'),
        ('teacher', '0011_assignmentsubmission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accept_late_submissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment-materials/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='release_marks_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(_release_existing_marks, _unrelease),
    ]
