# Generated by Django 6.0.7 on 2026-08-24 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos', '0010_schoolsetting_logo'),
        ('results', '0008_backfill_term_order'),
        ('teacher', '0012_assignment_accept_late_submissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('mock', 'Mock Exam'), ('other', 'Other')], default='final', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=120)),
                ('instructions', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exam_papers', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='teacher.class')),
                ('exam_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='dos.examschedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_papers', to='results.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='results.academicterm')),
            ],
            options={
                'db_table': 'exam_papers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='exam_papers_status_0d08cf_idx'), models.Index(fields=['teacher', 'status'], name='exam_papers_teacher_014e59_idx')],
            },
        ),
    ]
