# Generated by Django 6.0.8 on 2026-09-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_exampaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_backtracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_method',
            field=models.CharField(choices=[('upload', 'Upload a file'), ('in_person', 'Hand in physically')], default='in_person', max_length=10),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
