# Generated by Django 6.0.8 on 2026-09-17 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0009_assessment_assessment_student_term_idx_and_more'),
        ('teacher', '0014_assignment_submission_method_backtracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('video', 'Video')], default='file', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='teaching-materials/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='teacher.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='results.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_materials', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='results.academicterm')),
            ],
            options={
                'db_table': 'teaching_materials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['class_obj', 'term'], name='teaching_ma_class_o_fbc2d1_idx')],
            },
        ),
    ]
