# Generated by Django 6.0.1 on 2026-07-02 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'db_table': 'audit_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='audit_entri_action_db6795_idx'), models.Index(fields=['-created_at'], name='audit_entri_created_996502_idx')],
            },
        ),
    ]
