# Generated by Django 6.0.7 on 2026-08-30 02:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0008_backfill_term_order'),
        ('student', '0006_remove_assignmentsubmission_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'db_table': 'finance_expense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='RWF', max_length=8)),
                ('receipt_prefix', models.CharField(default='RCT', max_length=12)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('bank_details', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'finance settings',
                'db_table': 'finance_settings',
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('bursary_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('arrangement', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_account', to='student.student')),
            ],
            options={
                'db_table': 'finance_student_accounts',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate)),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile money'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('waiver', 'Waiver / bursary'), ('other', 'Other')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approvals', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='results.academicterm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'finance_expenses',
                'ordering': ['-spent_on', '-created_at'],
                'indexes': [models.Index(fields=['status', 'spent_on'], name='finance_exp_status_d981fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile money'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('waiver', 'Waiver / bursary'), ('other', 'Other')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('receipt_no', models.CharField(max_length=40, unique=True)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='student.fee')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_receipts', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reversals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payments',
                'ordering': ['-paid_on', '-created_at'],
                'indexes': [models.Index(fields=['fee', 'reversed_at'], name='finance_pay_fee_id_5ab80f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(choices=[('tuition', 'Tuition Fees'), ('transport', 'Transport'), ('lunch', 'Lunch Program'), ('uniform', 'Uniform'), ('activity', 'Activity Fee'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='results.academicterm')),
            ],
            options={
                'db_table': 'finance_fee_structures',
                'ordering': ['grade', 'category'],
                'unique_together': {('term', 'grade', 'section', 'category')},
            },
        ),
    ]
