# Generated by Django 6.0.7 on 2026-09-01 16:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('results', '0009_assessment_assessment_student_term_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('cash', 'Cash box'), ('bank', 'Bank account'), ('mobile', 'Mobile money')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_cash_accounts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'income categories',
                'db_table': 'finance_income_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_approved', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='results.academicterm')),
            ],
            options={
                'db_table': 'finance_budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'finance_budget_lines',
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile money'), ('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('waiver', 'Waiver / bursary'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='finance.cashaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.incomecategory')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_income_taken', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_income', to='results.academicterm')),
            ],
            options={
                'db_table': 'finance_other_income',
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('fee', 'Fee received'), ('income', 'Other income'), ('expense', 'Expense paid'), ('deposit', 'Banked'), ('withdrawal', 'Withdrawn'), ('transfer', 'Transfer'), ('adjustment', 'Correction')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('transfer_group', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.cashaccount')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='finance.expense')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='finance.feepayment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='finance.otherincome')),
            ],
            options={
                'db_table': 'finance_cash_movements',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='finance.cashaccount')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_approved', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='finance.expense')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payroll_runs',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_account', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='finance.payrollrun')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payslips',
                'ordering': ['staff_name'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_on', models.DateField(default=django.utils.timezone.localdate)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('counted_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.cashaccount')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_reconciliations',
                'ordering': ['-counted_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_account', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'staff salaries',
                'db_table': 'finance_staff_salaries',
                'ordering': ['staff__last_name', 'staff__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('term', 'name'), name='finance_budget_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='finance_budget_line_unique_category'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['account', '-occurred_on'], name='finance_cas_account_20cce3_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['kind', '-occurred_on'], name='finance_cas_kind_4b414d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'paid'])), fields=('period_year', 'period_month'), name='finance_payroll_one_live_run_per_month'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'staff'), name='finance_payslip_once_per_run'),
        ),
    ]
