# Generated by Django 6.0.8 on 2026-09-15 00:12

import apps.finance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def keep_existing_flat_rates(apps, schema_editor):
    """
    Salaries set up before PAYE bands keep the flat rate the bursar typed, so
    next month's payslips do not change without anyone choosing that. A
    salary with no tax rate set moves to the bands.
    """
    StaffSalary = apps.get_model('finance', 'StaffSalary')
    StaffSalary.objects.filter(tax_percent__gt=0).update(tax_method='flat')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashaccount_incomecategory_budget_budgetline_and_more'),
        ('student', '0006_remove_assignmentsubmission_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='paye_bands',
            field=models.JSONField(blank=True, default=apps.finance.models.rwanda_paye_bands),
        ),
        migrations.AddField(
            model_name='otherincome',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.otherincome'),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='tax_method',
            field=models.CharField(choices=[('paye', 'PAYE bands'), ('flat', 'Flat rate')], default='paye', max_length=4),
        ),
        migrations.RunPython(keep_existing_flat_rates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('receipt_no', 'fee'), name='finance_payment_receipt_fee_unique'),
        ),
    ]
