# Generated by Django 6.0.8 on 2026-09-15 10:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


DEFAULT_CATEGORIES = [
    ('tuition', 'Tuition'), ('boarding', 'Boarding'), ('lunch', 'Lunch'),
    ('transport', 'Transport'), ('uniform', 'Uniform'), ('activity', 'Activities'),
    ('exam', 'Examination fee'), ('pta', 'PTA contribution'),
    ('development', 'Development levy'), ('medical', 'Medical insurance'),
    ('admission', 'Admission fee'), ('arrears', 'Brought forward'), ('other', 'Other'),
]


def carry_over(apps, schema_editor):
    """
    Move each school onto the new fee setup without changing a single bill.

    * Categories: the defaults, plus any code already on a charge.
    * Each fee line's year and stream become its class list.
    * Charges a line already raised are linked to it, so invoicing again does
      not bill those families a second time. Before, the only guard was "has
      a charge of this category this term", which is exactly what is matched.
    """
    FeeCategory = apps.get_model('finance', 'FeeCategory')
    FeeStructure = apps.get_model('finance', 'FeeStructure')
    StructureCharge = apps.get_model('finance', 'StructureCharge')
    Fee = apps.get_model('student', 'Fee')

    for order, (code, name) in enumerate(DEFAULT_CATEGORIES):
        FeeCategory.objects.get_or_create(code=code, defaults={'name': name, 'sort_order': order})
    for code in Fee.objects.values_list('category', flat=True).distinct():
        if code:
            FeeCategory.objects.get_or_create(
                code=code[:20], defaults={'name': code.replace('_', ' ').title()})

    for line in FeeStructure.objects.all():
        line.classes = [{'grade': line.grade, 'stream': line.section or ''}] if line.grade else []
        line.name = ''
        line.save(update_fields=['classes', 'name'])
        fees = Fee.objects.filter(term_id=line.term_id, category=line.category,
                                  student__grade=line.grade, source__isnull=True)
        if line.section:
            fees = fees.filter(student__section=line.section)
        for fee in fees:
            if not StructureCharge.objects.filter(structure=line, student_id=fee.student_id).exists():
                StructureCharge.objects.create(structure=line, student_id=fee.student_id,
                                               fee=fee, instalment=1)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_carried_balances'),
        ('results', '0009_assessment_assessment_student_term_idx_and_more'),
        ('student', '0006_remove_assignmentsubmission_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'fee categories',
                'db_table': 'finance_fee_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['category', 'name', 'created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='boarding',
            field=models.CharField(choices=[('all', 'Boarders and day students'), ('boarders', 'Boarders only'), ('day', 'Day students only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('term', 'Every term'), ('year', 'Once a year'), ('once', 'Once per student')], default='term', max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='instalments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='intake',
            field=models.CharField(choices=[('all', 'New and returning students'), ('new', 'New students only'), ('returning', 'Returning students only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='fee_lines', to='student.student'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scope', models.CharField(choices=[('students', 'Chosen students'), ('siblings', 'Siblings'), ('boarders', 'Boarders'), ('day', 'Day students'), ('all', 'Everyone')], default='students', max_length=10)),
                ('from_child', models.PositiveSmallIntegerField(default=2)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='fee_discounts', to='student.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='results.academicterm')),
            ],
            options={
                'db_table': 'finance_fee_discounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StructureCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instalment', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='student.fee')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='finance.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_charges', to='student.student')),
            ],
            options={
                'db_table': 'finance_structure_charges',
                'unique_together': {('structure', 'student', 'instalment')},
            },
        ),
        migrations.RunPython(carry_over, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='feestructure',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='section',
        ),
    ]
