# Generated by Django 6.0.8 on 2026-10-08 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payroll_on_staff_register'),
        ('student', '0008_student_medical_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=15)),
                ('provider_ref', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the parent to approve'), ('successful', 'Paid and receipted'), ('failed', 'Failed or declined'), ('needs_review', 'Paid, but the office must place it')], default='pending', max_length=12)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('receipt_no', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='student.student')),
            ],
            options={
                'db_table': 'finance_online_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
