# Generated by Django 6.0.1 on 2026-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_invitation_class_obj'),
        ('student', '0002_student_fee_alter_activityenrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_invitations', to='student.student'),
        ),
    ]
