# Generated by Django 6.0.1 on 2026-05-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_invitation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='linked_email',
            field=models.EmailField(blank=True, default='', help_text='For parent invitations: stores the student email to auto-link on registration.', max_length=254),
        ),
    ]
