# Generated by Django 6.0.7 on 2026-08-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_twofactorconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('dos', 'Director of Studies'), ('matron', 'Matron'), ('discipline', 'Director of Discipline'), ('librarian', 'Librarian'), ('admin', 'Administrator')], max_length=10),
        ),
    ]
