# Generated by Django 6.0.1 on 2026-03-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_fee_studentdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='term',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_student_1ff8ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_grade_9a2fa6_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_status_3ac771_idx',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='student',
        ),
    ]
