# Generated by Django 6.0.1 on 2026-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_student_and_more'),
        ('authentication', '0006_alter_invitation_student'),
        ('behavior', '0002_alter_behaviorreport_student_and_more'),
        ('discipline', '0003_alter_boardingstudent_student_and_more'),
        ('parents', '0003_remove_fee_student_remove_fee_term_and_more'),
        ('results', '0003_alter_assessment_student_alter_result_student'),
        ('student', '0002_student_fee_alter_activityenrollment_student_and_more'),
        ('teacher', '0003_alter_classassignment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentstudentrelationship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='student.student'),
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentDocument',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
