# Generated by Django 6.0.1 on 2026-07-02 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_alter_parentstudentrelationship_student_and_more'),
        ('student', '0003_quiz_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consent_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_responses', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='parents.consentrequest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_responses', to='student.student')),
            ],
            options={
                'db_table': 'consent_responses',
                'unique_together': {('request', 'student')},
            },
        ),
    ]
