# Generated by Django 6.0.7 on 2026-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_consentrequest_consentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrequest',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
