# Generated by Django 6.0.1 on 2026-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
