# Generated by Django 6.0.1 on 2026-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
        ('student', '0002_student_fee_alter_activityenrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_reports', to='student.student'),
        ),
        migrations.AlterField(
            model_name='conductgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_grades', to='student.student'),
        ),
    ]
