# Generated by Django 6.0.1 on 2026-06-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_behaviorreport_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorreport',
            name='marks_deducted',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
