# Generated by Django 6.0.6 on 2026-07-10 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0004_add_marks_deducted'),
        ('student', '0003_quiz_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='behaviorreport',
            index=models.Index(fields=['status', 'date'], name='behavior_re_status_841e66_idx'),
        ),
    ]
