# Generated by Django 6.0.7 on 2026-08-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0005_behaviorreport_behavior_re_status_841e66_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductgrade',
            options={'ordering': ['-term__year', '-term__order']},
        ),
    ]
