import { describe, it, expect } from 'vitest'
import { readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { collectIconNames } from '../../scripts/fetch-fonts.mjs'

/**
 * The icon font is subset to the icons this app renders (27 KB instead of
 * 361 KB). The trade is that adding a new icon without re-running
 * `npm run fonts` leaves it out of the font, and it renders as its own name in
 * plain text — silently, in production.
 *
 * The scan itself is imported from the fetch script rather than reimplemented
 * here. An earlier version of this test duplicated the logic, and when the
 * script's scan turned out to miss icons passed as data (`{ icon: 'dashboard' }`
 * in the nav configs) the test missed them in exactly the same way and passed
 * while the sidebar was broken. One implementation, used by both.
 */

const ROOT = process.cwd()
const manifest = JSON.parse(readFileSync(join(ROOT, 'scripts/icons.manifest.json'), 'utf8'))
/* Google's official names, cached by the fetch script — this is what separates
   a real icon from an identifier that happens to look like one. */
const official = new Set(JSON.parse(readFileSync(join(ROOT, 'scripts/icon-names.cache.json'), 'utf8')))

describe('material symbols subset', () => {
    it('ships a manifest and a font file', () => {
        expect(manifest.icons.length).toBeGreaterThan(100)
        expect(statSync(join(ROOT, 'public/fonts/material-symbols-subset.woff2')).size).toBeGreaterThan(1000)
    })

    it('carries every icon the app can render', () => {
        const shipped = new Set(manifest.icons)
        const missing = collectIconNames(official, join(ROOT, 'src')).filter(n => !shipped.has(n))

        expect(
            missing,
            'These icons are rendered but are not in the font subset, so they will '
            + 'show as their own name in plain text. Run `npm run fonts`:\n  '
            + missing.join('\n  '),
        ).toEqual([])
    })

    it('the scan itself finds icons passed as data, not just literals in a span', () => {
        /* Asserts against the SCAN, not the manifest. Checking the manifest here
           proved worthless: the manifest is generated by this same scan, so if
           the scan regresses both sides move together and the test still passes.
           These five all arrive through nav/stat config objects — exactly what
           the first version of the scan could not see. */
        const found = collectIconNames(official, join(ROOT, 'src'))
        for (const icon of ['dashboard', 'assessment', 'settings', 'account_circle', 'analytics']) {
            expect(found, `${icon} is named in a config object, not inside a span`).toContain(icon)
        }
    })
})
