# Generated by Django 6.0.7 on 2026-07-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantprovision'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
