# Generated by Django 6.0.7 on 2026-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_existing_operators_keep_their_powers'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(blank=True, default='', max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='platformuser',
            name='mfa_last_step',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
