# Generated by Django 6.0.1 on 2026-03-24 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_nightattendance'),
        ('student', '0002_student_fee_alter_activityenrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardingstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_info', to='student.student'),
        ),
        migrations.AlterField(
            model_name='diningplan',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_plans', to='student.student'),
        ),
        migrations.AlterField(
            model_name='studentleader',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_roles', to='student.student'),
        ),
    ]
