# Generated by Django 6.0.1 on 2026-06-03 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0007_seed_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisFacilitySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed'), ('na', 'Not Applicable')], default='na', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dis_facility_sections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='disfacility',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='discipline.disfacilitysection'),
        ),
    ]
