# Generated by Django 6.0.7 on 2026-07-19 01:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0009_seed_dorm_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'dormitories',
                'db_table': 'dormitories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DormRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('bed_capacity', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='discipline.dormitory')),
            ],
            options={
                'db_table': 'dorm_rooms',
                'ordering': ['dormitory__name', 'room_number'],
                'unique_together': {('dormitory', 'room_number')},
            },
        ),
    ]
