# Generated by Django 6.0.8 on 2026-10-08 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0010_dormitory_dormroom'),
        ('student', '0007_student_dietary_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExeatPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_type', models.CharField(choices=[('weekend', 'Weekend leave'), ('medical', 'Medical / hospital'), ('family', 'Family matter'), ('event', 'Event or competition'), ('other', 'Other')], default='weekend', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('departure_at', models.DateTimeField()),
                ('expected_return_at', models.DateTimeField()),
                ('actual_return_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('out', 'Out of school'), ('returned', 'Returned')], default='requested', max_length=20)),
                ('parent_approval', models.CharField(choices=[('pending', 'Awaiting parent'), ('approved', 'Parent approved'), ('declined', 'Parent declined')], default='pending', max_length=20)),
                ('parent_note', models.CharField(blank=True, max_length=200)),
                ('gate_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exeat_passes_created', to=settings.AUTH_USER_MODEL)),
                ('gate_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exeat_gate_checks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exeat_passes', to='student.student')),
            ],
            options={
                'db_table': 'exeat_passes',
                'ordering': ['-departure_at'],
                'indexes': [models.Index(fields=['status', 'departure_at'], name='exeat_passe_status_d19762_idx')],
            },
        ),
    ]
